--- #YAML:1.0
name:               Code-Class-C
version:            0.07
abstract:           Perl extension for creating ANSI C code from a set
author:
    - Tom Kirchner <tk@apple.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
